steps:
    - name: 'gcr.io/cloud-builders/docker'
      args:
          - 'build'
          - '--tag=gcr.io/develop-matsushima/scraping'
          - '--file=./dockerfile'
          - '.'
images:
    - 'gcr.io/develop-matsushima/scraping'