# Generated by Django 4.2.6 on 2023-12-15 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app1_horse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorsePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'app1_horsplase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tan', models.IntegerField(default=0)),
                ('fuku_1', models.IntegerField(default=0)),
                ('fuku_2', models.IntegerField(default=0)),
                ('fuku_3', models.IntegerField(default=0)),
                ('umaren', models.IntegerField(default=0)),
                ('umatan', models.IntegerField(default=0)),
                ('wide_12', models.IntegerField(default=0)),
                ('wide_13', models.IntegerField(default=0)),
                ('wide_23', models.IntegerField(default=0)),
                ('trio', models.IntegerField(default=0)),
                ('tierce', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app1_horsplase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('race_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=datetime.datetime(2023, 12, 15, 17, 8, 35, 430279, tzinfo=datetime.timezone.utc))),
                ('is_votable', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app1_race',
                'managed': False,
            },
        ),
    ]
