# name: Deploy with Terraform

# on:
#   pull_request:
#     types: [closed]
#     branches: [main]

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Apply
#         run: terraform apply -auto-approve
#         env:
#           TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
#           TF_VAR_api_key: ${{ secrets.API_KEY }}
#           TF_VAR_db_name: ${{ secrets.DB_name }}
#           TF_VAR_db_user: ${{ secrets.DB_USER }}
#           TF_VAR_db_host: ${{ secrets.DB_HOST }}
#           TF_VAR_django_debug: ${{secrets.DJANGO_DEBUG }}
